CREATE DATABASE PROJETBAOVOLA2929;

USE PROJETBAOVOLA2929;

CREATE TABLE STATUS (
    ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    NAME NVARCHAR(255) NOT NULL
);

CREATE TABLE USER (
    ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD NVARCHAR(255) NOT NULL,
    ISADMIN TINYINT NOT NULL
);

CREATE TABLE CATEGORY (
    ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PICTURE VARCHAR(255),
    IDCATEGORY INT NOT NULL,
    FOREIGN KEY (IDCATEGORY) REFERENCES CATEGORY(ID)
);

CREATE TABLE USER_FAVORITE (
    ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    IDUSER INT NOT NULL,
    ADDEDON DATETIME NOT NULL,
    REMOVEDON DATETIME NULL,
    IDPRODUCT INT NOT NULL,
    FOREIGN KEY (IDUSER) REFERENCES USER(ID),
    FOREIGN KEY (IDPRODUCT) REFERENCES PRODUCT(ID)
);

CREATE TABLE USER_CART (
    ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    IDUSER INT NOT NULL,
    ADDEDON DATETIME NOT NULL,
    DELETEDAT DATETIME NULL,
    BOUGHTON DATETIME NULL,
    QUANTITY INT NOT NULL,
    IDPRODUCT INT NOT NULL,
    FOREIGN KEY (IDUSER) REFERENCES USER(ID),
    FOREIGN KEY (IDPRODUCT) REFERENCES PRODUCT(ID)
);

CREATE TABLE ORDER_GLOBAL (
    ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    IDUSER INT NOT NULL,
    ORDERDATE DATETIME NOT NULL,
    TOTALVALUE DOUBLE NULL,
    STATUS INT NOT NULL,
    FOREIGN KEY (IDUSER) REFERENCES USER(ID),
    FOREIGN KEY (STATUS) REFERENCES STATUS(ID)
);

CREATE TABLE `ORDER` (
    ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    IDUSER INT NOT NULL,
    IDCART INT NOT NULL,
    PARENTORDER INT NULL,
    FOREIGN KEY (IDUSER) REFERENCES USER(ID),
    FOREIGN KEY (IDCART) REFERENCES USER_CART(ID),
    FOREIGN KEY (PARENTORDER) REFERENCES ORDER_GLOBAL(ID)
);

--Nouvelle tables à créer
CREATE TABLE STOCK_MOVEMENT (
    ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    PRODUCTID INT NOT NULL,
    DATEMOVEMENT DATETIME NOT NULL,
    QUANTITY INT NOT NULL,
    FOREIGN KEY (PRODUCTID) REFERENCES PRODUCT(ID) ON DELETE CASCADE
);

CREATE TABLE PRICE (
    ID INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
    IDPRODUCT INT NOT NULL,
    PRICEVALUE DOUBLE NOT NULL,
    ADDEDON DATETIME NOT NULL,
    DELETEDON DATETIME NULL,
    FOREIGN KEY (IDPRODUCT) REFERENCES PRODUCT(ID)
);